server:
  port: 8082

spring:
  application:
    name: ms_flies
  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

profiles:
  active: dev